CUDA_VISIBLE_DEVICES=0 python tools/train.py configs/faceseg/swin_base_ours_seg_cls_15_embed_256_cloud_ce_dice_no_attn1.py
CUDA_VISIBLE_DEVICES=0 python tools/train.py configs/faceseg/swin_base_ours_seg_cls_15_embed_256_cloud_ce_dice_no_attn2.py
