CUDA_VISIBLE_DEVICES=3 python tools/train.py configs/faceseg/swin_base_ours_seg_cls_15_embed_256_cloud_ce_dice_no_attn1.py
CUDA_VISIBLE_DEVICES=4 python tools/train.py configs/faceseg/swin_base_ours_seg_cls_15_embed_256_cloud_ce_dice_no_attn2.py
CUDA_VISIBLE_DEVICES=3 python tools/train.py configs/faceseg/swin_base_ours_seg_cls_15_embed_256_cloud_ce_dice_no_attn12.py
CUDA_VISIBLE_DEVICES=3 python tools/train.py configs/faceseg/swin_base_ours_seg_cls_15_embed_256_cloud_ce_dice_tranform_layer_2.py
CUDA_VISIBLE_DEVICES=3 python tools/train.py configs/faceseg/swin_base_ours_seg_cls_15_embed_256_cloud_ce_dice_tranform_layer_3.py